name: Build & Push to GitHub Container Registry

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout codice
        uses: actions/checkout@v4

      - name: Login su GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build e push MS1 — Employee Service
        uses: docker/build-push-action@v5
        with:
          context: ./employee-service
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/employee-service:latest

      - name: Build e push MS2 — Salary Analytics
        uses: docker/build-push-action@v5
        with:
          context: ./salary-analytics
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/salary-analytics:latest
